export const COMPONENTS = {
  TEXT_FIELD: 'TEXT_FIELD',
  SELECT_BOX: 'SELECT_BOX',
  CHECKBOX: 'CHECKBOX',
  RADIO: 'RADIO',
  AUTOCOMPLETE: 'AUTOCOMPLETE',
  DATEPICKER: 'DATEPICKER',
  TEXT_AREA: 'TEXT_AREA',
  MULTI_SELECT_BOX: 'MULTI_SELECT_BOX',
  BUTTON: 'BUTTON',
  LINK: 'LINK',
  NONE: 'NONE',
  TYPOGRAPHY: 'TYPOGRAPHY',
  ICON: 'ICON'
};
